<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="SignalmappingOutput" Id="{2bdbb390-18c0-4372-a0ff-04e8c4b60455}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SignalmappingOutput]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* ==================================== Digitale Ausgaenge ====================================*)
	
	GVL.mb_Input_Coils[0] := Emitter_Rollenband4m;
	GVL.mb_Input_Coils[3] := StartLED;
	GVL.mb_Input_Coils[4] := StopLED;
	GVL.mb_Input_Coils[5] := ResetLED;
	GVL.mb_Input_Coils[6] := HomeLED;
	GVL.mb_Input_Coils[7] := QuitLED;
	GVL.mb_Input_Coils[9] := Foerderband_Vorwaerts;
	GVL.mb_Input_Coils[10] := Foerderband_Rueckwaerts;
	GVL.mb_Input_Coils[11] := AufzugFoerderbandVorwaerts;
	GVL.mb_Input_Coils[12] := AufzugFoerderbandRueckwaerts;
	GVL.mb_Input_Coils[14] := RBGGabelLinks;
	GVL.mb_Input_Coils[15] := RBGGabelRechts;
	GVL.mb_Input_Coils[17] := RFIDExecuteCommand;
	GVL.mb_Input_Coils[20] := DigitalStackerCraneGabelLinks;
	GVL.mb_Input_Coils[21] := DigitalStackerCraneGabelRechts;
	GVL.mb_Input_Coils[22] := DigitalStackerCraneLiftGabel;
	GVL.mb_Input_Coils[26]	:=	PositionerClamp;
	GVL.mb_Input_Coils[27]	:=	PositionerRaise;

(* ==================================== Analoge Ausgaenge ====================================*)
	GVL.mb_Input_Registers[0] := AufzugSollwert;
	GVL.mb_Input_Registers[1] := RBGSollwertX;
	GVL.mb_Input_Registers[2] := RBGSollwertZ;
	GVL.mb_Input_Registers[3] := RFIDCommand;
	GVL.mb_Input_Registers[4] := RFIDWriteData;
	GVL.mb_Input_Registers[5] := RFIDMemoryIndex;
	GVL.mb_Input_Registers[7] := DigitalStackerCraneTargetPos;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>